### ISSUE TITLE
Please release molotov 1.5

### ISSUE THREAD

**Issue by Natim** [loads/molotov#113]
I would be interested in a release of molotov, to be able to benefit from useful fixes that happened in master.

Mainly this one: 

https://github.com/loads/molotov/commit/4e786204de73db1bcb2683d10564a1d2e90bfb29#diff-8fcde73d405ce2638a358fd7791105dcR23

**Comment by tarekziade** [comment]
I am waiting for feedback on #107 to make sure the logic is good - once it's closed I can release 1.5

**Comment by Natim** [comment]
Thanks
