### ISSUE TITLE
reconsider resolving of request hostnames

### ISSUE THREAD

**Issue by pjenvey** [loads/molotov#119]
The auto-resolving of request hostnames is [disabled for https requests](https://github.com/loads/molotov/blob/542d793/molotov/util.py#L77) as it could cause the address in the certificate to no longer match.

The similar situation could unknowingly occur in plain http requests: consider a hawk authentication header that ties itself to the request's original hostname.

**Comment by tarekziade** [comment]
good idea, we could add --disable-dns-resolve
