### ISSUE TITLE
make molotov work with the latest aiohttp

### ISSUE THREAD

**Issue by tarekziade** [loads/molotov#125]
a bunch of options have been deprecated, that we need to fix

**Comment by tarekziade** [comment]
The first one is getting read of unread_data() -- I am not sure how to replace it in https://github.com/loads/molotov/blob/master/molotov/listeners.py#L90

Maybe @asvetlov could hint ? :)

**Comment by tarekziade** [comment]
The second one is using `ClientSession` as a base class so we can print the request and response when doing verbose mode, https://github.com/loads/molotov/blob/master/molotov/session.py#L34 
not sure either what would be a good replacement

**Comment by asvetlov** [comment]
Hi. At first glance, you can solve your needs by registering a custom [Client Tracing](https://docs.aiohttp.org/en/stable/client_advanced.html#client-tracing) event handlers.

Please let me know if these handlers don't satisfy your request.

**Comment by tarekziade** [comment]
@asvetlov thanks, it looks like the cleanest way to do it. There's one thing I was not able to do with those hooks:
`molotov` resolves the host when doing the load testing on non-ssl urls, so it  changes the host on the fly with the IP. It looks like those trace hooks are not allowing it (FrozenInstanceError). What would be a good way to call the DNS resolver on simple session.[get|post|etc] calls?

Thanks @asvetlov

**Comment by asvetlov** [comment]
Do you resolve IP for logging IP addresses instead of DNS names or for caching resolved IPs for speed?
If later -- you can write a custom [resolver](https://docs.aiohttp.org/en/stable/client_advanced.html#resolving-using-custom-nameservers) that internally redirects lookups to threaded or async resolvers (or do this in another way of your choice).

https://github.com/aio-libs/aiohttp/blob/master/aiohttp/resolver.py

**Comment by tarekziade** [comment]
it's for caching resolved IPs for speed, see https://github.com/loads/molotov/blob/master/molotov/session.py#L105 and https://github.com/loads/molotov/blob/master/molotov/util.py#L61

but looking again at the code, I guess I can do this directy in the connector and not have to call it in each request()

**Comment by asvetlov** [comment]
IIRC TCPConnector does DNS caching itself

**Comment by tarekziade** [comment]
Thanks @asvetlov

**Comment by asvetlov** [comment]
Welcome!
