### ISSUE TITLE
Latest version (2.2) not available in PyPI

### ISSUE THREAD

**Issue by kyleparrott** [loads/molotov#131]
It looks like a Github release for version 2.2 was created on Dec 9 but the latest version available in PyPI is 2.1. Are there any blocking issues preventing the upload/release of version 2.2? It looks like all previous releases are available. 

Thanks in advance for any insight on this.

**Comment by pymen** [comment]
+1

**Comment by n1ngu** [comment]
Hi @tarekziade , sorry for the spam. I'm addressing you as the main contributor of this project because this seemed a 0-headache issue but it's been a while now.

I hope your are doing just fine. I fear there is little the community can help here, but tell us otherwise.

**Comment by tarekziade** [comment]
@n1ngu Hi ! sorry I have been neglecting the project. Would you like to help me maintaining it?

**Comment by n1ngu** [comment]
@tarekziade I watch this repo because it is a fun asyncio project to play around, but maintaining the codebase is a different story! But I would be glad to help with any packaging issue (I know they can be a burden for most people, I don't understand why I like it)

**Comment by tarekziade** [comment]
Molotov 2.2 and 2.3 released

https://pypi.org/project/molotov/

@n1ngu thanks ! I will keep that in mind for the next release.
