### ISSUE TITLE
single hit / scenario mode

### ISSUE THREAD

**Issue by tarekziade** [loads/molotov#20]
we should add a way to run a single scenario once, for testing purpose.

I guess by adding a 'name' option to scenario(name='something')

and then calling it with --scenario-name and --hits=1

**Comment by tarekziade** [comment]
Maybe a simpler way it to point the function e.g.  molotov pkg.module.func

for --hits it's going to be hard to control it unless it's a single worker and a single process. So we should make sure it's launched with -w 1 -p1

**Comment by rpappalax** [comment]
yea, this is good.   we're gonna add a step to our loadtesting process to do a quick 1 pass (sanity check) across the API(s) to verify if a stack is working, before we go to all the trouble of spinning up an attack cluster.
