### ISSUE TITLE
create a generic moloslave-based image

### ISSUE THREAD

**Issue by tarekziade** [loads/molotov#22]
using python3.5-slim

**Comment by tarekziade** [comment]
@rpappalax is working on it!

**Comment by tarekziade** [comment]
Simple example:

```
FROM python:3.5-slim

RUN apt-get update
RUN apt-get install -y git
RUN pip3 install git+https://github.com/loads/molotov.git

CMD moloslave $TEST_REPO $TEST_NAME
```

And then the docker image can be run against a Github repo that contains a molotov.json file.

**Comment by rpappalax** [comment]
@tarekziade  I assume we'll probably want to host this on dockerhub?  if so, we have a dockerhub account:  firefoxtesteng.  I know we talked about possibly speeding things up by putting our image in S3 or ECR, but I wonder if it's more understandible/accessible to community if we leave it in dockerhub?

**Comment by tarekziade** [comment]
+1 for dockerhub

**Comment by tarekziade** [comment]
see https://github.com/loads/molotov-docker
