### ISSUE TITLE
add metrics reporting to molotov

### ISSUE THREAD

**Issue by rpappalax** [loads/molotov#23]
@tarek We frequently have intermittent failures with loadtests that seem to be due to AWS network hiccups.  This happens in particular w/ long-running tests we've done w/ ap-loadtester.
@pjenvey suggested we might start collecting metrics from within molotov to log things like test start/stop times, etc. to determine when tests fail (or connections dropped) due to latency.

With loads, we've talked about setting up InfluxDB for this.  Not sure the best way ultimately for us to gather (and monitor) this data.

**Comment by tarekziade** [comment]
ah! I've just removed statsd from molotov, but I can add it back , so the load test sends some metrics with a few --statsd-* options

DO you want to provide a first list of statsd metrics you would like to see? (and their type)

**Comment by tarekziade** [comment]
integrate with https://github.com/scivey/aiostatsd 
+explain how it gets installed on mac os x
+ provide a session.statsd link for scenario to do their own statsd calls

**Comment by rpappalax** [comment]
thanks!

**Comment by tarekziade** [comment]
I added a timer for each unique endpoint called for now

**Comment by amirouche** [comment]
What is the current way to extract success, failures and timings?
