### ISSUE TITLE
Write a tutorial

### ISSUE THREAD

**Issue by tarekziade** [loads/molotov#28]
content:

- [x] how to use Molostart
- [x] how to write a test
- [x] how to run in with several workers, then several processes
- [x] how to add statsd metrics
- [x] how to use Moloslave
- [x] how to deploy it for loads-broker, using Docker

**Comment by rpappalax** [comment]
@stephendonner and i can review

**Comment by tarekziade** [comment]
The tutorial has been added. Ready for reviews anytime
