### ISSUE TITLE
printing requests assumes payload is text

### ISSUE THREAD

**Issue by willkg** [loads/molotov#30]
https://github.com/loads/molotov/blob/5ab8c822fcd3c515b4614d624a4d67c9c7d5d40d/molotov/session.py#L85

That assumes that if the request body is bytes, then it must be utf-8. Antenna load tests send gzip compressed payloads, so this isn't true.

Maybe we can check the HTTP headers to see what the payload is before figuring out how to convert and print it to stdout? Maybe check to see how much data there is before printing it? If there's more than 1000 bytes, probably makes sense to truncate it.

**Comment by tarekziade** [comment]
Hey @willkg -- very good point, thanks. I'll go ahead and improve that

**Comment by tarekziade** [comment]
I changed the behavior, could you look at it & try it ? let me know if that's good !

**Comment by willkg** [comment]
That works great for my issue. Thank you!

**Comment by tarekziade** [comment]
\\o/
