### ISSUE TITLE
quickstart script that generates a load test layout

### ISSUE THREAD

**Issue by rpappalax** [loads/molotov#31]
Would include things like:
- Makefile (should be fully parameterized pulling all values from molotov.json or loadtest.env)
- Dockerfile (should be fully parameterized pulling all values from molotov.json or loadtest.env)
- molotov.json (with sample values)
- loads.tpl (with sample values)

NOTE: 
currently we use loadtest.env to specify all key,value params (for Makefile and Dockerfile). 
We should replace this with either a molotov.json or molotov.yaml

**Comment by tarekziade** [comment]
> Dockerfile

I don't think we need this if we build a generic Docker image that just takes a github repo in the env

**Comment by tarekziade** [comment]
work in progress in https://github.com/loads/molotov/pull/32

**Comment by tarekziade** [comment]
For Docker, see https://github.com/loads/molotov/issues/22#issuecomment-280003606
