### ISSUE TITLE
Add function to generate a dummy FxA account and FXA_BEARER_TOKEN

### ISSUE THREAD

**Issue by rpappalax** [loads/molotov#33]

**Comment by chartjes** [comment]
As a follow-up to @tarekziade's comment in IRC, I am not sure this sort of thing belongs inside molotov itself. Clearly it's some kind of helper method and probably belongs in some other module

**Comment by tarekziade** [comment]
Maybe we can have a loads-recipe or molotov-recipes repository where there's an example on how to use FXA tokens

**Comment by rpappalax** [comment]
yea, that's a good point.  i think a 'recipes' repo is a good idea, but it seems like something that would quickly become outdated because folks usually create recipes then walk away from them.  perhaps a molotov-utils repo?  FxA is mozilla-centric and wouldn't be well-placed here, but we could very well want a bundle of utilities that our centric to the testing we do in mozilla-services.  molotov-mozutils?  i dunno.  what do u guys think

**Comment by tarekziade** [comment]
added a repo for this https://github.com/loads/mozlotov
