### ISSUE TITLE
Molotov reporting inconsistent test results

### ISSUE THREAD

**Issue by m8ttyB** [loads/molotov#38]
I executed a test run against a service that returned a `HTTP 503` and the test results reported back were inconsistent.

```
**** Molotov v0.4. Happy breaking! ****
[6399] Preparing 1 workers...OK
SUCCESSES: 0 | FAILURES: 0
0 OK, 1 Failed

**Comment by tarekziade** [comment]
Yes, this is something I have noticed. The reason is that on shutdown the SUCCESSES... line is not updated so you get a small inconsistency.

This is now fixed, thanks for reporting! I am closing it, assuming it worked, but I case you still see the problem please feel free to reopen. 

Thanks Mat
