### ISSUE TITLE
add a sleep per run

### ISSUE THREAD

**Issue by tarekziade** [loads/molotov#48]
like 

https://github.com/mozilla-services/ap-loadtester/blob/master/aplt/scenarios.py#L80

**Comment by tarekziade** [comment]
Do we want to be able to  change the delay from one run to the other using a command line option or do we want that delay to always be the same ?

cc @rpappalax @pdehaan

**Comment by rpappalax** [comment]
As you point out, autopush ap-loadtester provides for a run delays for scenarios (i.e. https://github.com/mozilla-services/ap-loadtester/blob/master/aplt/scenarios.py#L92) which is handy for throttling execution on a per scenario basis.  This feature gets a lot of use when testing autopush and i assume it would be for most projects.  Being able to throttle/control every aspect of a run can make the difference between a desirable load and one that is out of control and/or not particularly useful.
This feature sounds good for molotov 👍

**Comment by tarekziade** [comment]
So, do you want that option to surface as a command line option, or something that's done by code like in ap-loadtester? What would be ideal?

**Comment by rpappalax** [comment]
if we do it by cli arg only, it would be useful for ad-hoc testing, but wouldn't be easy to use w/ one of the brokers.  Both ways are useful but for different use cases.  Molotov is great because it can be used both for ad-hoc testing as well as together w/ a broker.

Possible to have both ways?

**Comment by tarekziade** [comment]
I am going to add two options:

- --delay : a delay after each run of a worker, applied for every scenario
- @scenario(weight, delay) : a delay specifically for the scenario being run. adds up with --delay

boths are seconds. in float.
