### ISSUE TITLE
rename to molotov

### ISSUE THREAD

**Issue by tarekziade** [loads/molotov#5]

**Comment by rpappalax** [comment]
@tarekziade what's wrong with cosmpolitan? ;)

**Comment by rpappalax** [comment]
@tarekziade @chartjes Do we have a longer term vision for this? Right now this adds a decorator for weighted tests.  Are there other features we may want to add to tests in future?  If so, perhaps this should have a name indicating that it's a catch-all, helper lib of sorts: loadtest-utils??
The Makefile also provides some swiss-army knife types operations for packaging your tests to run with loads-broker so we should take that into consideration when naming this.

**Comment by tarekziade** [comment]
I think the scope of Molotov is to let people :

- create a load test script against a service, using vanilla python
- provide a CLI to run a load test locally
- make it easy to embed in a distributed test using loads

So I don't think it requires to be named after Loads as it's fairly standalone.

**Comment by tarekziade** [comment]
I am going to make the assumption that works for you @rpappalax because I want to hack on this this week-end, but if that name does not sound good we can always revert of course

**Comment by tarekziade** [comment]
I am forking it here for now so in case some tests are linking to this repo they don't get broken

https://github.com/tarekziade/ailoads
