### ISSUE TITLE
Bad generated code on `@global_setup`

### ISSUE THREAD

**Issue by peterbe** [loads/molotov#55]
I ran the `molostart` command line tool and started editing `loadtest.py`. Then when I run it I got this:

```
▶ molotov --max-runs 1 -cx loadtest.py
**** Molotov v1.0. Happy breaking! ****
Traceback (most recent call last):
  File "/Users/peterbe/virtualenvs/tecken-loadtests/bin/molotov", line 11, in <module>
    sys.exit(main())
  File "/Users/peterbe/virtualenvs/tecken-loadtests/lib/python3.5/site-packages/molotov/run.py", line 98, in main
    return run(args)
  File "/Users/peterbe/virtualenvs/tecken-loadtests/lib/python3.5/site-packages/molotov/run.py", line 108, in run
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "loadtest.py", line 11, in <module>
    @global_setup
TypeError: global_setup() takes 0 positional arguments but 1 was given
```

The code generated looked like this:

```python
...MY STUFF...

@global_setup
def test_starts(args):
    """ This functions is called before anything starts.

    Notice that it's not a coroutine.
    """

    ...MY STUFF...
```

**Comment by peterbe** [comment]
Actually, the description of this issue is probably wrong due to my lack of understanding of how molotov works. 

The Traceback talks about `loadtest.py` on line 11. In my `loadtest.py` line 11 is:
```python
import random
```

**Comment by peterbe** [comment]
Actually, in https://molotov.readthedocs.io/en/latest/fixtures/ it says to use `molotov.global_setup()` (note the `()` call). 
That's different from the code generated with `molostart`. 

In my case, it doesn't matter if I change. something else must be broken about how `molotov --max-runs 1 -cx loadtest.py` works.

**Comment by peterbe** [comment]
Crap! Ignore comment number 2 and comment 3. What happened was that I ran `molotov` in the wrong directory. That's why I got a "strange" traceback. 

Nevertheless, the generated code by `molostart` did lack `()` on all decorators.

**Comment by tarekziade** [comment]
Thanks for finding that issue!
