### ISSUE TITLE
Allow for slowly ramping up load tests

### ISSUE THREAD

**Issue by chartjes** [loads/molotov#61]
While testing a different project there was a desire to have load tests that start off with a low number of workers and gradually build up to a larger number of workers to better simulate expected load on the service.

**Comment by tarekziade** [comment]
We can add a --ramp-time option, that will introduce workers gradually, from 0 to n. A new worker is added (each ramp-time / n) seconds.

**Comment by tarekziade** [comment]
I will add a linear ramp up - I guess it's good enough.
