### ISSUE TITLE
Improved shutdown

### ISSUE THREAD

**Issue by tarekziade** [loads/molotov#67]
When the duration is over -- display a message in case some requests are still pending

On SIGKILL shutdown, display a message asking for confirmation if there are some pending requests

cc @chartjes

**Comment by tarekziade** [comment]
also, the current loop shutdown is ugly and can be improved

**Comment by tarekziade** [comment]
for instance, ending the sizing does not go through all the worker teardowns.
we also need to avoid sleeping when the worker is not started yet. we need a trigger (like an event, or smaller sleeps, or an alarm)

**Comment by rpappalax** [comment]
sometimes molotov will hang at end of test - particularly if the server-under-test has high latency.  traffic generation clearly terminates but the end of test acknowledgement / report never happens.

**Comment by tarekziade** [comment]
I think an interactive confirmation is overkill. the new mode implemented in #107 is good enough - once we've validated with @rpappalax that it works as expected.
