### ISSUE TITLE
Allow recording request/response stats into CSV file

### ISSUE THREAD

**Issue by undera** [loads/molotov#80]
Hi,
Would you consider writing raw data into simple text format, for further analysis by other scripts? Something like JMeter/Grinder/Gatling already do, where one request-response pair has one record in CSV with sufficient fields like response time, time to first byte, request label, bytes counts etc.

That would allow to plug Molotov into other solutions which use this approach of writing file and analysing it after test or in parallel. Namely Taurus Tool or Jenkins Performance Plugin.

**Comment by undera** [comment]
Another option would be some way to plug in custom class to get request-response information, so it will decide itself how to write the results, into text or binary format, or to send over network.

**Comment by tarekziade** [comment]
This is an excellent idea @undera 

what we could do is change the calls to print_request and print_session in session.py so it's pluggable. One thing to keep in mind is to make it compatible with multiple processes like I did with the sharedconsole, so we don't have conflicts when writing in the file.

Maube we can come up with a base class that does all the heavy lifting, and have shareconsole use it, and then whatever custom class;

would you like to tackle this?

**Comment by undera** [comment]
I'm not very familiar with codebase, but having some base class would definitely be a way.

Sorry, I don't understand the question of "tackling", my English is not that good.

**Comment by tarekziade** [comment]
tackling here means doing the coding  :)

**Comment by undera** [comment]
I'm sorry, I don't think I understand codebase well enough to code this plugging piece.

**Comment by tarekziade** [comment]
@undera I have implemented the feature at https://github.com/loads/molotov/pull/82 
would you like to review the API before I merge to see if it fits your need ?

**Comment by tarekziade** [comment]
@peterbe I guess that's something you've also asked for

**Comment by undera** [comment]
@tarekziade I have looked at the source code and I don't understand how would I plug my class in? I want to avoid modifying source code and having own fork. Some sort of command-line parameter, or config file or environment variable. 
My point is that I don't want to have this as part of testing scripts. I assume test scripts live their own life and result analysis lives independent life, being part of testing infrastructure. I see that `session_events` is sufficient for my needs, just need a way to have it as separate "bootstrap" code.
Thoughts?

**Comment by tarekziade** [comment]
I build it as a decorator so as long as the module containing this decorator is imported, it will work.
I can also add a command line option if that makes it easier. Can you think of how it would look like ?

**Comment by undera** [comment]
What if I will call molotov to run programmatically? I think of a wrapper way like this:
```python
@molotov.session_events()
async def event(session, event, **data):
    print(event)

molotov.run.main()
```

Will if function fine in this case, when decorator is called earlier than molotov run?

**Comment by tarekziade** [comment]
yes that should work because the decorator just add the event function in a registry, so when the runner looks for it it will find it

**Comment by undera** [comment]
Then current PR looks sufficient for what I need.

**Comment by tarekziade** [comment]
ok. I can also add something like that so you don't have to do this bootstrap:

```
$ molotov --event-listener package.module.event 
```

where event is your undecorated function. would that make it easier ?

**Comment by undera** [comment]
Yes, it's another way, also works for me.

**Comment by peterbe** [comment]
> @peterbe I guess that's something you've also asked for

Sorry, I honestly can't remember. It would certainly help for understanding what molotov is doing. 

I think the thing I asked for what to have molotov spit out a report/summary at the end, just like boom, wrk or ab does.

**Comment by tarekziade** [comment]
@peterbe that's what this feature is for. The event listener gets every HTTP request and response, so is the basis for building whatever client-side report you want. @undera will use it to create a CSV report to consume it in jenkins, but it can be a stdout report if you want.  (which is what you wanted afair)

**Comment by tarekziade** [comment]
@undera I merged the work in master. Do you mind giving it a shot before I release a new version with this feature ? thanks!

**Comment by undera** [comment]
Thanks! Will give it a try in the nearest time.
