### ISSUE TITLE
release 1.4

### ISSUE THREAD

**Issue by tarekziade** [loads/molotov#93]
Hey @dmand  - the current master is ready to be released as 1.4 - would you like to add/test/verify anything before I push it ?

Thanks

**Comment by dmand** [comment]
Hi.

I've tested molotov/master after the last week's merges (i have a molotov extension that works with events, collects test metrics and performs further analytics) and it worked beautifully to me. So judging from my end the project is ready for new release.

**Comment by dmand** [comment]
Thank you for getting this merged and helping along the way.

**Comment by tarekziade** [comment]
Nice! I'll release later today. 

If your extension is public and you're willing to, I'd love to have a link to it in Molotov documentation to show people how it's used.

**Comment by tarekziade** [comment]
1.4 released
