### ISSUE TITLE
lots of ServerDisconnectedError errors and all requests failing

### ISSUE THREAD

**Issue by vangheem** [loads/molotov#95]
However, doing the same requests outside of molotov work just fine.

I'm on:

- aiohttp 2.2.5
- molotov 1.4

Any idea what is going wrong?

```
@scenario(100)
async def foobar(session):
    async with session.get(MY_URL) as resp:
        await resp.text()
```

but when I replace it with:

```
@scenario(100)
async def foobar(_):
    async with aiohttp.ClientSession() as session:
        async with session.get(MY_URL) as resp:
            await resp.text()
```

everything works fine.

Something is closing the session when it probably should not?

**Comment by tarekziade** [comment]
Looks like your server closes the socket after each request, which is not an usual behavior. In your second working example, it's likely that if you do two get() calls in a row with the same session, the second will fail.

If it's not an intended behavior, I'd fix the server. (also, check for keep-alive)

If it's an intended behavior, what you did is the right approach, but it means that the load test will have to recreate a session everytime it's doing a request, which is suboptimal. I am not sure if aiohttp has a mechanism to reopen an existing session, I will investigate. Maybe @asvetlov could enlight us here :) 

In any case we should include that mechanism in Molotov, so you don't have to worry about that inside the test, when you deal with a server that closes the socket on each request.

**Comment by vangheem** [comment]
Okay, I see why this is probably happening on my end as well. I've been testing with haproxy in front of the application and it has the `option http-server-close` on.

Thanks for the response.

**Comment by tarekziade** [comment]
Ok cool, I'll keep this bug open to improve Molotov when this happens
