### ISSUE TITLE
Run from a Python script to be able to debug?

### ISSUE THREAD

**Issue by mrsarm** [loads/molotov#97]
Because Molotov run from a bash-like console, you cannot debug your scenarios with a proper IDE like PyCharm.

Is there a way to run Molotov from a Python script? Maybe invoking your scenarios from a function, with the same parameters available from the command line.

**Comment by tarekziade** [comment]
You can run molotov from a script by calling the main() function in the run module:

```python
from molotov.run import main

main()
```
